insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1409, 'Guttenberg Information Technologies Center', 2, '0',616453,788276, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1410, 'Guttenberg Information Technologies Center', 2, '0',616454,788276, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1411, 'Guttenberg Information Technologies Center', 2, '0',616455,788276, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1412, 'Guttenberg Information Technologies Center', 2, '0',616452,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1413, 'Guttenberg Information Technologies Center', 2, '0',616453,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1414, 'Guttenberg Information Technologies Center', 2, '0',616454,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1415, 'Guttenberg Information Technologies Center', 2, '0',616455,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1416, 'Guttenberg Information Technologies Center', 2, '0',616456,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1417, 'Guttenberg Information Technologies Center', 2, '0',616457,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1418, 'Guttenberg Information Technologies Center', 2, '0',616452,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1419, 'Guttenberg Information Technologies Center', 2, '0',616453,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1420, 'Guttenberg Information Technologies Center', 2, '0',616454,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1421, 'Guttenberg Information Technologies Center', 2, '0',616455,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1422, 'Guttenberg Information Technologies Center', 2, '0',616456,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1423, 'Guttenberg Information Technologies Center', 2, '0',616457,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1424, 'Guttenberg Information Technologies Center', 2, '0',616458,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1425, 'Guttenberg Information Technologies Center', 2, '0',616452,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1426, 'Guttenberg Information Technologies Center', 2, '0',616453,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1427, 'Guttenberg Information Technologies Center', 2, '0',616454,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1428, 'Guttenberg Information Technologies Center', 2, '0',616455,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1429, 'Guttenberg Information Technologies Center', 2, '0',616456,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1430, 'Guttenberg Information Technologies Center', 2, '0',616457,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1431, 'Guttenberg Information Technologies Center', 2, '0',616453,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1432, 'Guttenberg Information Technologies Center', 2, '0',616454,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1433, 'Guttenberg Information Technologies Center', 2, '0',616455,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1434, 'Guttenberg Information Technologies Center', 2, '0',616456,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1435, 'Guttenberg Information Technologies Center', 2, '0',616457,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1436, 'Guttenberg Information Technologies Center', 2, '0',616456,788281, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1437, 'Guttenberg Information Technologies Center', 3, '0',616453,788276, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1438, 'Guttenberg Information Technologies Center', 3, '0',616454,788276, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1439, 'Guttenberg Information Technologies Center', 3, '0',616455,788276, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1440, 'Guttenberg Information Technologies Center', 3, '0',616452,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1441, 'Guttenberg Information Technologies Center', 3, '0',616453,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1442, 'Guttenberg Information Technologies Center', 3, '0',616454,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1443, 'Guttenberg Information Technologies Center', 3, '0',616455,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1444, 'Guttenberg Information Technologies Center', 3, '0',616456,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1445, 'Guttenberg Information Technologies Center', 3, '0',616457,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1446, 'Guttenberg Information Technologies Center', 3, '0',616452,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1447, 'Guttenberg Information Technologies Center', 3, '0',616453,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1448, 'Guttenberg Information Technologies Center', 3, '0',616454,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1449, 'Guttenberg Information Technologies Center', 3, '0',616455,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1450, 'Guttenberg Information Technologies Center', 3, '0',616456,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1451, 'Guttenberg Information Technologies Center', 3, '0',616457,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1452, 'Guttenberg Information Technologies Center', 3, '0',616458,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1453, 'Guttenberg Information Technologies Center', 3, '0',616452,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1454, 'Guttenberg Information Technologies Center', 3, '0',616453,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1455, 'Guttenberg Information Technologies Center', 3, '0',616454,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1456, 'Guttenberg Information Technologies Center', 3, '0',616455,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1457, 'Guttenberg Information Technologies Center', 3, '0',616456,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1458, 'Guttenberg Information Technologies Center', 3, '0',616457,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1459, 'Guttenberg Information Technologies Center', 3, '0',616453,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1460, 'Guttenberg Information Technologies Center', 3, '0',616454,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1461, 'Guttenberg Information Technologies Center', 3, '0',616455,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1462, 'Guttenberg Information Technologies Center', 3, '0',616456,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1463, 'Guttenberg Information Technologies Center', 3, '0',616457,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1464, 'Guttenberg Information Technologies Center', 3, '0',616456,788281, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1465, 'Guttenberg Information Technologies Center', 4, '0',616453,788276, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1466, 'Guttenberg Information Technologies Center', 4, '0',616454,788276, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1467, 'Guttenberg Information Technologies Center', 4, '0',616455,788276, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1468, 'Guttenberg Information Technologies Center', 4, '0',616452,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1469, 'Guttenberg Information Technologies Center', 4, '0',616453,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1470, 'Guttenberg Information Technologies Center', 4, '0',616454,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1471, 'Guttenberg Information Technologies Center', 4, '0',616455,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1472, 'Guttenberg Information Technologies Center', 4, '0',616456,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1473, 'Guttenberg Information Technologies Center', 4, '0',616457,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1474, 'Guttenberg Information Technologies Center', 4, '0',616452,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1475, 'Guttenberg Information Technologies Center', 4, '0',616453,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1476, 'Guttenberg Information Technologies Center', 4, '0',616454,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1477, 'Guttenberg Information Technologies Center', 4, '0',616455,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1478, 'Guttenberg Information Technologies Center', 4, '0',616456,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1479, 'Guttenberg Information Technologies Center', 4, '0',616457,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1480, 'Guttenberg Information Technologies Center', 4, '0',616458,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1481, 'Guttenberg Information Technologies Center', 4, '0',616452,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1482, 'Guttenberg Information Technologies Center', 4, '0',616453,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1483, 'Guttenberg Information Technologies Center', 4, '0',616454,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1484, 'Guttenberg Information Technologies Center', 4, '0',616455,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1485, 'Guttenberg Information Technologies Center', 4, '0',616456,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1486, 'Guttenberg Information Technologies Center', 4, '0',616457,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1487, 'Guttenberg Information Technologies Center', 4, '0',616453,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1488, 'Guttenberg Information Technologies Center', 4, '0',616454,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1489, 'Guttenberg Information Technologies Center', 4, '0',616455,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1490, 'Guttenberg Information Technologies Center', 4, '0',616456,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1491, 'Guttenberg Information Technologies Center', 4, '0',616457,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1492, 'Guttenberg Information Technologies Center', 4, '0',616456,788281, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1493, 'Guttenberg Information Technologies Center', 5, '0',616453,788276, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1494, 'Guttenberg Information Technologies Center', 5, '0',616454,788276, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1495, 'Guttenberg Information Technologies Center', 5, '0',616455,788276, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1496, 'Guttenberg Information Technologies Center', 5, '0',616452,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1497, 'Guttenberg Information Technologies Center', 5, '0',616453,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1498, 'Guttenberg Information Technologies Center', 5, '0',616454,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1499, 'Guttenberg Information Technologies Center', 5, '0',616455,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1500, 'Guttenberg Information Technologies Center', 5, '0',616456,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1501, 'Guttenberg Information Technologies Center', 5, '0',616457,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1502, 'Guttenberg Information Technologies Center', 5, '0',616452,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1503, 'Guttenberg Information Technologies Center', 5, '0',616453,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1504, 'Guttenberg Information Technologies Center', 5, '0',616454,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1505, 'Guttenberg Information Technologies Center', 5, '0',616455,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1506, 'Guttenberg Information Technologies Center', 5, '0',616456,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1507, 'Guttenberg Information Technologies Center', 5, '0',616457,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1508, 'Guttenberg Information Technologies Center', 5, '0',616458,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1509, 'Guttenberg Information Technologies Center', 5, '0',616452,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1510, 'Guttenberg Information Technologies Center', 5, '0',616453,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1511, 'Guttenberg Information Technologies Center', 5, '0',616454,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1512, 'Guttenberg Information Technologies Center', 5, '0',616455,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1513, 'Guttenberg Information Technologies Center', 5, '0',616456,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1514, 'Guttenberg Information Technologies Center', 5, '0',616457,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1515, 'Guttenberg Information Technologies Center', 5, '0',616453,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1516, 'Guttenberg Information Technologies Center', 5, '0',616454,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1517, 'Guttenberg Information Technologies Center', 5, '0',616455,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1518, 'Guttenberg Information Technologies Center', 5, '0',616456,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1519, 'Guttenberg Information Technologies Center', 5, '0',616457,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1520, 'Guttenberg Information Technologies Center', 5, '0',616456,788281, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1521, 'Guttenberg Information Technologies Center', 6, '0',616453,788276, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1522, 'Guttenberg Information Technologies Center', 6, '0',616454,788276, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1523, 'Guttenberg Information Technologies Center', 6, '0',616455,788276, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1524, 'Guttenberg Information Technologies Center', 6, '0',616452,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1525, 'Guttenberg Information Technologies Center', 6, '0',616453,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1526, 'Guttenberg Information Technologies Center', 6, '0',616454,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1527, 'Guttenberg Information Technologies Center', 6, '0',616455,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1528, 'Guttenberg Information Technologies Center', 6, '0',616456,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1529, 'Guttenberg Information Technologies Center', 6, '0',616457,788277, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1530, 'Guttenberg Information Technologies Center', 6, '0',616452,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1531, 'Guttenberg Information Technologies Center', 6, '0',616453,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1532, 'Guttenberg Information Technologies Center', 6, '0',616454,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1533, 'Guttenberg Information Technologies Center', 6, '0',616455,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1534, 'Guttenberg Information Technologies Center', 6, '0',616456,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1535, 'Guttenberg Information Technologies Center', 6, '0',616457,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1536, 'Guttenberg Information Technologies Center', 6, '0',616458,788278, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1537, 'Guttenberg Information Technologies Center', 6, '0',616452,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1538, 'Guttenberg Information Technologies Center', 6, '0',616453,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1539, 'Guttenberg Information Technologies Center', 6, '0',616454,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1540, 'Guttenberg Information Technologies Center', 6, '0',616455,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1541, 'Guttenberg Information Technologies Center', 6, '0',616456,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1542, 'Guttenberg Information Technologies Center', 6, '0',616457,788279, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1543, 'Guttenberg Information Technologies Center', 6, '0',616453,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1544, 'Guttenberg Information Technologies Center', 6, '0',616454,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1545, 'Guttenberg Information Technologies Center', 6, '0',616455,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1546, 'Guttenberg Information Technologies Center', 6, '0',616456,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1547, 'Guttenberg Information Technologies Center', 6, '0',616457,788280, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1548, 'Guttenberg Information Technologies Center', 6, '0',616456,788281, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1549, 'Cypress Residence Hall', 2, '0',616450,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1550, 'Cypress Residence Hall', 2, '0',616450,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1551, 'Cypress Residence Hall', 2, '0',616451,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1552, 'Cypress Residence Hall', 2, '0',616450,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1553, 'Cypress Residence Hall', 2, '0',616451,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1554, 'Cypress Residence Hall', 2, '0',616449,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1555, 'Cypress Residence Hall', 2, '0',616450,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1556, 'Cypress Residence Hall', 3, '0',616450,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1557, 'Cypress Residence Hall', 3, '0',616450,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1558, 'Cypress Residence Hall', 3, '0',616451,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1559, 'Cypress Residence Hall', 3, '0',616450,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1560, 'Cypress Residence Hall', 3, '0',616451,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1561, 'Cypress Residence Hall', 3, '0',616449,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1562, 'Cypress Residence Hall', 3, '0',616450,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1563, 'Cypress Residence Hall', 4, '0',616450,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1564, 'Cypress Residence Hall', 4, '0',616450,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1565, 'Cypress Residence Hall', 4, '0',616451,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1566, 'Cypress Residence Hall', 4, '0',616450,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1567, 'Cypress Residence Hall', 4, '0',616451,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1568, 'Cypress Residence Hall', 4, '0',616449,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1569, 'Cypress Residence Hall', 4, '0',616450,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1570, 'Cypress Residence Hall', 5, '0',616450,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1571, 'Cypress Residence Hall', 5, '0',616450,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1572, 'Cypress Residence Hall', 5, '0',616451,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1573, 'Cypress Residence Hall', 5, '0',616450,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1574, 'Cypress Residence Hall', 5, '0',616451,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1575, 'Cypress Residence Hall', 5, '0',616449,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1576, 'Cypress Residence Hall', 5, '0',616450,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1577, 'Cypress Residence Hall', 6, '0',616450,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1578, 'Cypress Residence Hall', 6, '0',616450,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1579, 'Cypress Residence Hall', 6, '0',616451,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1580, 'Cypress Residence Hall', 6, '0',616450,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1581, 'Cypress Residence Hall', 6, '0',616451,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1582, 'Cypress Residence Hall', 6, '0',616449,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1583, 'Cypress Residence Hall', 6, '0',616450,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1584, 'Cypress Residence Hall', 7, '0',616450,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1585, 'Cypress Residence Hall', 7, '0',616450,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1586, 'Cypress Residence Hall', 7, '0',616451,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1587, 'Cypress Residence Hall', 7, '0',616450,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1588, 'Cypress Residence Hall', 7, '0',616451,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1589, 'Cypress Residence Hall', 7, '0',616449,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1590, 'Cypress Residence Hall', 7, '0',616450,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1591, 'Cypress Residence Hall', 8, '0',616450,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1592, 'Cypress Residence Hall', 8, '0',616450,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1593, 'Cypress Residence Hall', 8, '0',616451,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1594, 'Cypress Residence Hall', 8, '0',616450,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1595, 'Cypress Residence Hall', 8, '0',616451,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1596, 'Cypress Residence Hall', 8, '0',616449,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1597, 'Cypress Residence Hall', 8, '0',616450,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1598, 'Cypress Residence Hall', 9, '0',616450,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1599, 'Cypress Residence Hall', 9, '0',616450,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1600, 'Cypress Residence Hall', 9, '0',616451,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1601, 'Cypress Residence Hall', 9, '0',616450,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1602, 'Cypress Residence Hall', 9, '0',616451,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1603, 'Cypress Residence Hall', 9, '0',616449,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1604, 'Cypress Residence Hall', 9, '0',616450,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1629, 'Van Houten Library', 2, '0',616460,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1630, 'Van Houten Library', 2, '0',616461,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1631, 'Van Houten Library', 2, '0',616459,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1632, 'Van Houten Library', 2, '0',616460,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1633, 'Van Houten Library', 2, '0',616461,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1634, 'Van Houten Library', 2, '0',616459,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1635, 'Van Houten Library', 2, '0',616460,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1636, 'Van Houten Library', 2, '0',616459,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1637, 'Van Houten Library', 2, '0',616460,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1638, 'Van Houten Library', 3, '0',616460,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1639, 'Van Houten Library', 3, '0',616461,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1640, 'Van Houten Library', 3, '0',616459,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1641, 'Van Houten Library', 3, '0',616460,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1642, 'Van Houten Library', 3, '0',616461,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1643, 'Van Houten Library', 3, '0',616459,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1644, 'Van Houten Library', 3, '0',616460,788252, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1645, 'Van Houten Library', 3, '0',616459,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1646, 'Van Houten Library', 3, '0',616460,788253, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1647, 'Mechanical Enginnering Center', 2, '0',616456,788249, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1648, 'Mechanical Enginnering Center', 2, '0',616457,788249, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1649, 'Mechanical Enginnering Center', 2, '0',616458,788249, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1650, 'Mechanical Enginnering Center', 2, '0',616456,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1651, 'Mechanical Enginnering Center', 2, '0',616457,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1652, 'Mechanical Enginnering Center', 2, '0',616458,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1653, 'Mechanical Enginnering Center', 2, '0',616459,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1654, 'Mechanical Enginnering Center', 2, '0',616456,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1655, 'Mechanical Enginnering Center', 2, '0',616457,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1656, 'Mechanical Enginnering Center', 2, '0',616458,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1657, 'Mechanical Enginnering Center', 3, '0',616456,788249, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1658, 'Mechanical Enginnering Center', 3, '0',616457,788249, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1659, 'Mechanical Enginnering Center', 3, '0',616458,788249, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1660, 'Mechanical Enginnering Center', 3, '0',616456,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1661, 'Mechanical Enginnering Center', 3, '0',616457,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1662, 'Mechanical Enginnering Center', 3, '0',616458,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1663, 'Mechanical Enginnering Center', 3, '0',616459,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1664, 'Mechanical Enginnering Center', 3, '0',616456,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1665, 'Mechanical Enginnering Center', 3, '0',616457,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1666, 'Mechanical Enginnering Center', 3, '0',616458,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1667, 'Mechanical Enginnering Center', 4, '0',616456,788249, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1668, 'Mechanical Enginnering Center', 4, '0',616457,788249, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1669, 'Mechanical Enginnering Center', 4, '0',616458,788249, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1670, 'Mechanical Enginnering Center', 4, '0',616456,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1671, 'Mechanical Enginnering Center', 4, '0',616457,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1672, 'Mechanical Enginnering Center', 4, '0',616458,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1673, 'Mechanical Enginnering Center', 4, '0',616459,788250, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1674, 'Mechanical Enginnering Center', 4, '0',616456,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1675, 'Mechanical Enginnering Center', 4, '0',616457,788251, 'N');
insert into "APP"."AREA" ("SQAURE_ID", "SQUARE_DESC", "FLOOR_NUM", "ROOM_NUM", "TILE_X", "TILE_Y", "COVERED_IND") values(1676, 'Mechanical Enginnering Center', 4, '0',616458,788251, 'N');
